name: SyncProto
on: [push]

jobs:
  protoJobs:
    runs-on: [ubuntu-latest]
    steps:
      - name: Sync Proto Files
        uses: adrianjost/files-sync-action@v1.0.1
        with:
          FILE_PATTERNS: |
            ^proto/.*
          TARGET_REPOS: |
            tarsidi-danesh/grpc-intro-java
            tarsidi-danesh/grpc-intro-go
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
      - name: Create Tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}
      - name: Create Event
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: proto-synced
          client-payload: '{ "version": "${{ steps.tag_version.outputs.new_tag }}" }'
